### PR TITLE
add linux_ppc64le

### PR DESCRIPTION
**Pull request by gillins**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@conda-forge/qca can this be merged? I'm hoping to get `qgis` builds for ppc out.. I've taken the liberty of adding myself and @SrNetoChan as maintainers - hope that's ok.

**Comment by izahn** [comment]
Thank you for your contribution, and for volunteering to co-maintain, great to have you.

**Comment by gillins** [comment]
Thanks @izahn !

**Pull request merged**
