### PR TITLE
try osx arm 64 and linux aarch64

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This is necessary for building QGIS in osx_arm64 and linux_aarch64
conda-forge/qgis-feedstock#289

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
Aparently this is working. @gillins wanna give it a look and see if it's what we need for QGIS?

**Comment by gillins** [comment]
Looks good

**Comment by SrNetoChan** [comment]
@ceholden @izahn can we merge this?

**Pull request merged**
