### PR TITLE
Adds openssl as host dependency

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Trying to fix an issue in QGIS trying to use old Open SSL for QCA OpenSSL plugin
https://github.com/conda-forge/qgis-feedstock/issues/299

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
@h-vetinari Does it look good for you? @gillins ?

**Comment by gillins** [comment]
Yep looks good to me

**Comment by SrNetoChan** [comment]
@ceholden @izahn can any of you please merge this?

**Comment by ceholden** [comment]
> @ceholden @izahn can any of you please merge this?

Hey @SrNetoChan, sorry to be totally absentee. I'm a bit behind on conda-forge update but this looks good to me, I'll merge this in. Thank you!

**Comment by SrNetoChan** [comment]
Thank you!!

**Pull request merged**
